# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x11\x12\t\n\x01y\x18\x02 \x01(\x11\"\xe4\x01\n\x07Request\x12\x11\n\tget_image\x18\x01 \x01(\x08\x12\x0f\n\x07quality\x18\x02 \x01(\r\x12\x14\n\x0cprocess_name\x18\x03 \x01(\t\x12\x12\n\npress_keys\x18\x04 \x03(\t\x12\x14\n\x0crelease_keys\x18\x05 \x03(\t\x12\x15\n\x05mouse\x18\x06 \x01(\x0b\x32\x06.Point\x12\x1c\n\x0c\x63lient_mouse\x18\x07 \x01(\x0b\x32\x06.Point\x12\x10\n\x08get_keys\x18\x08 \x01(\x08\x12\x11\n\tget_mouse\x18\t \x01(\x08\x12\x1b\n\x13\x61llow_user_override\x18\n \x01(\x08\"U\n\x08Response\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\x12\x14\n\x0cpressed_keys\x18\x03 \x03(\t\x12\x15\n\x05mouse\x18\x04 \x01(\x0b\x32\x06.Pointb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POINT._serialized_start=18
  _POINT._serialized_end=47
  _REQUEST._serialized_start=50
  _REQUEST._serialized_end=278
  _RESPONSE._serialized_start=280
  _RESPONSE._serialized_end=365
# @@protoc_insertion_point(module_scope)
